// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package todo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TodoTaskEntity struct {
	ID                   int64     `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Task                 *TodoTask `protobuf:"bytes,2,opt,name=Task,proto3" json:"Task,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TodoTaskEntity) Reset()         { *m = TodoTaskEntity{} }
func (m *TodoTaskEntity) String() string { return proto.CompactTextString(m) }
func (*TodoTaskEntity) ProtoMessage()    {}
func (*TodoTaskEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *TodoTaskEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoTaskEntity.Unmarshal(m, b)
}
func (m *TodoTaskEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoTaskEntity.Marshal(b, m, deterministic)
}
func (m *TodoTaskEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoTaskEntity.Merge(m, src)
}
func (m *TodoTaskEntity) XXX_Size() int {
	return xxx_messageInfo_TodoTaskEntity.Size(m)
}
func (m *TodoTaskEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoTaskEntity.DiscardUnknown(m)
}

var xxx_messageInfo_TodoTaskEntity proto.InternalMessageInfo

func (m *TodoTaskEntity) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TodoTaskEntity) GetTask() *TodoTask {
	if m != nil {
		return m.Task
	}
	return nil
}

type TodoTask struct {
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	IsFininshed          bool     `protobuf:"varint,3,opt,name=IsFininshed,proto3" json:"IsFininshed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoTask) Reset()         { *m = TodoTask{} }
func (m *TodoTask) String() string { return proto.CompactTextString(m) }
func (*TodoTask) ProtoMessage()    {}
func (*TodoTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *TodoTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoTask.Unmarshal(m, b)
}
func (m *TodoTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoTask.Marshal(b, m, deterministic)
}
func (m *TodoTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoTask.Merge(m, src)
}
func (m *TodoTask) XXX_Size() int {
	return xxx_messageInfo_TodoTask.Size(m)
}
func (m *TodoTask) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoTask.DiscardUnknown(m)
}

var xxx_messageInfo_TodoTask proto.InternalMessageInfo

func (m *TodoTask) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TodoTask) GetIsFininshed() bool {
	if m != nil {
		return m.IsFininshed
	}
	return false
}

type GetTaskRequest struct {
	TaskID               int64    `protobuf:"varint,1,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskRequest) Reset()         { *m = GetTaskRequest{} }
func (m *GetTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GetTaskRequest) ProtoMessage()    {}
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *GetTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskRequest.Unmarshal(m, b)
}
func (m *GetTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskRequest.Marshal(b, m, deterministic)
}
func (m *GetTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskRequest.Merge(m, src)
}
func (m *GetTaskRequest) XXX_Size() int {
	return xxx_messageInfo_GetTaskRequest.Size(m)
}
func (m *GetTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskRequest proto.InternalMessageInfo

func (m *GetTaskRequest) GetTaskID() int64 {
	if m != nil {
		return m.TaskID
	}
	return 0
}

type GetTaskResponse struct {
	Task                 *TodoTaskEntity `protobuf:"bytes,1,opt,name=Task,proto3" json:"Task,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTaskResponse) Reset()         { *m = GetTaskResponse{} }
func (m *GetTaskResponse) String() string { return proto.CompactTextString(m) }
func (*GetTaskResponse) ProtoMessage()    {}
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *GetTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskResponse.Unmarshal(m, b)
}
func (m *GetTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskResponse.Marshal(b, m, deterministic)
}
func (m *GetTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskResponse.Merge(m, src)
}
func (m *GetTaskResponse) XXX_Size() int {
	return xxx_messageInfo_GetTaskResponse.Size(m)
}
func (m *GetTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskResponse proto.InternalMessageInfo

func (m *GetTaskResponse) GetTask() *TodoTaskEntity {
	if m != nil {
		return m.Task
	}
	return nil
}

type ListTasksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksRequest) Reset()         { *m = ListTasksRequest{} }
func (m *ListTasksRequest) String() string { return proto.CompactTextString(m) }
func (*ListTasksRequest) ProtoMessage()    {}
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{4}
}

func (m *ListTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksRequest.Unmarshal(m, b)
}
func (m *ListTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksRequest.Marshal(b, m, deterministic)
}
func (m *ListTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksRequest.Merge(m, src)
}
func (m *ListTasksRequest) XXX_Size() int {
	return xxx_messageInfo_ListTasksRequest.Size(m)
}
func (m *ListTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksRequest proto.InternalMessageInfo

type ListTasksResponse struct {
	Tasks                []*TodoTaskEntity `protobuf:"bytes,1,rep,name=Tasks,proto3" json:"Tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListTasksResponse) Reset()         { *m = ListTasksResponse{} }
func (m *ListTasksResponse) String() string { return proto.CompactTextString(m) }
func (*ListTasksResponse) ProtoMessage()    {}
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{5}
}

func (m *ListTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksResponse.Unmarshal(m, b)
}
func (m *ListTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksResponse.Marshal(b, m, deterministic)
}
func (m *ListTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksResponse.Merge(m, src)
}
func (m *ListTasksResponse) XXX_Size() int {
	return xxx_messageInfo_ListTasksResponse.Size(m)
}
func (m *ListTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksResponse proto.InternalMessageInfo

func (m *ListTasksResponse) GetTasks() []*TodoTaskEntity {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type AddTaskRequest struct {
	Task                 *TodoTask `protobuf:"bytes,1,opt,name=Task,proto3" json:"Task,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddTaskRequest) Reset()         { *m = AddTaskRequest{} }
func (m *AddTaskRequest) String() string { return proto.CompactTextString(m) }
func (*AddTaskRequest) ProtoMessage()    {}
func (*AddTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{6}
}

func (m *AddTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskRequest.Unmarshal(m, b)
}
func (m *AddTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskRequest.Marshal(b, m, deterministic)
}
func (m *AddTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskRequest.Merge(m, src)
}
func (m *AddTaskRequest) XXX_Size() int {
	return xxx_messageInfo_AddTaskRequest.Size(m)
}
func (m *AddTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskRequest proto.InternalMessageInfo

func (m *AddTaskRequest) GetTask() *TodoTask {
	if m != nil {
		return m.Task
	}
	return nil
}

type AddTaskResponse struct {
	Task                 *TodoTaskEntity `protobuf:"bytes,1,opt,name=Task,proto3" json:"Task,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddTaskResponse) Reset()         { *m = AddTaskResponse{} }
func (m *AddTaskResponse) String() string { return proto.CompactTextString(m) }
func (*AddTaskResponse) ProtoMessage()    {}
func (*AddTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{7}
}

func (m *AddTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskResponse.Unmarshal(m, b)
}
func (m *AddTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskResponse.Marshal(b, m, deterministic)
}
func (m *AddTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskResponse.Merge(m, src)
}
func (m *AddTaskResponse) XXX_Size() int {
	return xxx_messageInfo_AddTaskResponse.Size(m)
}
func (m *AddTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskResponse proto.InternalMessageInfo

func (m *AddTaskResponse) GetTask() *TodoTaskEntity {
	if m != nil {
		return m.Task
	}
	return nil
}

type UpdateTaskRequest struct {
	Task                 *TodoTaskEntity `protobuf:"bytes,1,opt,name=Task,proto3" json:"Task,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{8}
}

func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(m, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetTask() *TodoTaskEntity {
	if m != nil {
		return m.Task
	}
	return nil
}

type UpdateTaskResponse struct {
	Task                 *TodoTaskEntity `protobuf:"bytes,1,opt,name=Task,proto3" json:"Task,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateTaskResponse) Reset()         { *m = UpdateTaskResponse{} }
func (m *UpdateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskResponse) ProtoMessage()    {}
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{9}
}

func (m *UpdateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskResponse.Unmarshal(m, b)
}
func (m *UpdateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskResponse.Merge(m, src)
}
func (m *UpdateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskResponse.Size(m)
}
func (m *UpdateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskResponse proto.InternalMessageInfo

func (m *UpdateTaskResponse) GetTask() *TodoTaskEntity {
	if m != nil {
		return m.Task
	}
	return nil
}

func init() {
	proto.RegisterType((*TodoTaskEntity)(nil), "todo.TodoTaskEntity")
	proto.RegisterType((*TodoTask)(nil), "todo.TodoTask")
	proto.RegisterType((*GetTaskRequest)(nil), "todo.GetTaskRequest")
	proto.RegisterType((*GetTaskResponse)(nil), "todo.GetTaskResponse")
	proto.RegisterType((*ListTasksRequest)(nil), "todo.ListTasksRequest")
	proto.RegisterType((*ListTasksResponse)(nil), "todo.ListTasksResponse")
	proto.RegisterType((*AddTaskRequest)(nil), "todo.AddTaskRequest")
	proto.RegisterType((*AddTaskResponse)(nil), "todo.AddTaskResponse")
	proto.RegisterType((*UpdateTaskRequest)(nil), "todo.UpdateTaskRequest")
	proto.RegisterType((*UpdateTaskResponse)(nil), "todo.UpdateTaskResponse")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x6d, 0x9a, 0x7c, 0xfd, 0xda, 0x57, 0x88, 0x76, 0xd0, 0x1a, 0x7a, 0x2a, 0x7b, 0x0a, 0x1e,
	0x7a, 0xa8, 0x1e, 0x04, 0xb1, 0x2a, 0x54, 0xa5, 0x20, 0x1e, 0x42, 0xfd, 0x01, 0x91, 0x2c, 0x18,
	0xc4, 0x24, 0xba, 0xeb, 0xc1, 0xbf, 0xee, 0xc9, 0xcd, 0x66, 0x13, 0x93, 0xd4, 0x82, 0x3d, 0x65,
	0xf6, 0xcd, 0xbc, 0x79, 0x6f, 0x66, 0x08, 0x20, 0xd3, 0x28, 0x9d, 0x65, 0xef, 0xa9, 0x4c, 0xc9,
	0xc9, 0x63, 0xb6, 0x84, 0xbb, 0x56, 0xdf, 0x75, 0x28, 0x5e, 0x6e, 0x12, 0x19, 0xcb, 0x4f, 0x72,
	0xd1, 0x5d, 0x2d, 0x3d, 0x6b, 0x6a, 0xf9, 0x76, 0xa0, 0x22, 0x62, 0x70, 0xf2, 0xac, 0xd7, 0x55,
	0xc8, 0x70, 0xee, 0xce, 0x74, 0x8b, 0x92, 0x13, 0xe8, 0x1c, 0xbb, 0x42, 0xbf, 0x44, 0x88, 0xe0,
	0x3c, 0x84, 0xaf, 0x5c, 0xd7, 0x0f, 0x02, 0x1d, 0xd3, 0x14, 0xc3, 0x95, 0xb8, 0x8d, 0x93, 0x38,
	0x11, 0xcf, 0x3c, 0xf2, 0x6c, 0x95, 0xea, 0x07, 0x75, 0x88, 0xf9, 0x70, 0xef, 0xb8, 0xd4, 0x2d,
	0xf9, 0xdb, 0x07, 0x17, 0x92, 0xc6, 0xe8, 0xe5, 0xcf, 0xca, 0x8b, 0x79, 0xb1, 0x73, 0xec, 0x55,
	0x95, 0x22, 0x4b, 0x13, 0xc1, 0xc9, 0x37, 0x16, 0x2d, 0x6d, 0xf1, 0xa0, 0x69, 0xb1, 0x18, 0xcb,
	0x18, 0x25, 0xec, 0xdf, 0xc7, 0x42, 0xb3, 0x85, 0x11, 0x62, 0x97, 0x18, 0xd5, 0x30, 0xd3, 0xf2,
	0x18, 0xff, 0x34, 0xa0, 0x7a, 0xda, 0x5b, 0x7b, 0x16, 0x25, 0xec, 0x14, 0xee, 0x75, 0x14, 0xd5,
	0xbd, 0xb3, 0x86, 0xa1, 0xdf, 0x77, 0xa6, 0xe6, 0xa8, 0x58, 0x3b, 0xcf, 0x71, 0x81, 0xd1, 0x63,
	0x16, 0x85, 0x92, 0xd7, 0x55, 0xff, 0x4e, 0x5f, 0x80, 0xea, 0xf4, 0x5d, 0xe5, 0xe7, 0x5f, 0x96,
	0x2a, 0x55, 0x09, 0x3a, 0xc3, 0x7f, 0x73, 0x0c, 0x32, 0xf5, 0xcd, 0x2b, 0x4e, 0x0e, 0x5b, 0x68,
	0x21, 0xc5, 0x3a, 0xb4, 0xc0, 0xa0, 0xda, 0x3a, 0x8d, 0x8b, 0xaa, 0xf6, 0x69, 0x26, 0x47, 0x1b,
	0x78, 0xc5, 0x57, 0xca, 0x66, 0x7d, 0xa5, 0x72, 0xf3, 0x06, 0xa5, 0x72, 0x6b, 0xc7, 0x5a, 0x19,
	0x3f, 0xc3, 0x6f, 0x21, 0x7b, 0x05, 0xba, 0xb9, 0x24, 0xd6, 0x79, 0xea, 0xe9, 0xff, 0xe7, 0xe4,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x6c, 0x82, 0x96, 0x4d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoClient is the client API for Todo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoClient interface {
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error)
	UpdateTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error)
}

type todoClient struct {
	cc *grpc.ClientConn
}

func NewTodoClient(cc *grpc.ClientConn) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, "/todo.Todo/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, "/todo.Todo/ListTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error) {
	out := new(AddTaskResponse)
	err := c.cc.Invoke(ctx, "/todo.Todo/AddTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) UpdateTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error) {
	out := new(UpdateTaskResponse)
	err := c.cc.Invoke(ctx, "/todo.Todo/UpdateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServer is the server API for Todo service.
type TodoServer interface {
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	AddTask(context.Context, *AddTaskRequest) (*AddTaskResponse, error)
	UpdateTask(context.Context, *AddTaskRequest) (*UpdateTaskResponse, error)
}

// UnimplementedTodoServer can be embedded to have forward compatible implementations.
type UnimplementedTodoServer struct {
}

func (*UnimplementedTodoServer) GetTask(ctx context.Context, req *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (*UnimplementedTodoServer) ListTasks(ctx context.Context, req *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (*UnimplementedTodoServer) AddTask(ctx context.Context, req *AddTaskRequest) (*AddTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTask not implemented")
}
func (*UnimplementedTodoServer) UpdateTask(ctx context.Context, req *AddTaskRequest) (*UpdateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}

func RegisterTodoServer(s *grpc.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Todo/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Todo/ListTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Todo/AddTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).AddTask(ctx, req.(*AddTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Todo/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).UpdateTask(ctx, req.(*AddTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTask",
			Handler:    _Todo_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _Todo_ListTasks_Handler,
		},
		{
			MethodName: "AddTask",
			Handler:    _Todo_AddTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _Todo_UpdateTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
